<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-27T22:02:45 EET" name="Suite" finished-at="2021-07-27T22:03:11 EET" duration-ms="25296">
    <groups>
    </groups>
    <test started-at="2021-07-27T22:02:45 EET" name="Test" finished-at="2021-07-27T22:03:11 EET" duration-ms="25296">
      <class name="Tests.Home">
        <test-method is-config="true" signature="Basic()[pri:0, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:02:45 EET" name="Basic" finished-at="2021-07-27T22:02:52 EET" duration-ms="6518" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Basic -->
        <test-method signature="ClickOnOverviewDemo()[pri:1, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:02:52 EET" name="ClickOnOverviewDemo" finished-at="2021-07-27T22:02:53 EET" duration-ms="1047" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Tests.Home.ClickOnOverviewDemo(Home.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ClickOnOverviewDemo -->
        <test-method is-config="true" signature="close()[pri:0, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:02:53 EET" name="close" finished-at="2021-07-27T22:02:53 EET" duration-ms="82" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="Basic()[pri:0, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:02:53 EET" name="Basic" finished-at="2021-07-27T22:02:58 EET" duration-ms="5481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Basic -->
        <test-method signature="JoinNewsletterWithValidEmail()[pri:2, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:02:58 EET" name="JoinNewsletterWithValidEmail" finished-at="2021-07-27T22:02:59 EET" duration-ms="180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- JoinNewsletterWithValidEmail -->
        <test-method is-config="true" signature="close()[pri:0, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:02:59 EET" name="close" finished-at="2021-07-27T22:02:59 EET" duration-ms="155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="Basic()[pri:0, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:02:59 EET" name="Basic" finished-at="2021-07-27T22:03:04 EET" duration-ms="5339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Basic -->
        <test-method signature="ClickOnReadMore()[pri:3, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:03:04 EET" name="ClickOnReadMore" finished-at="2021-07-27T22:03:05 EET" duration-ms="845" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ClickOnReadMore -->
        <test-method is-config="true" signature="close()[pri:0, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:03:05 EET" name="close" finished-at="2021-07-27T22:03:05 EET" duration-ms="53" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="Basic()[pri:0, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:03:05 EET" name="Basic" finished-at="2021-07-27T22:03:10 EET" duration-ms="5366" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Basic -->
        <test-method signature="JoinNewsletterWithInvalidEmail()[pri:4, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:03:10 EET" name="JoinNewsletterWithInvalidEmail" finished-at="2021-07-27T22:03:11 EET" duration-ms="164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- JoinNewsletterWithInvalidEmail -->
        <test-method is-config="true" signature="close()[pri:0, instance:Tests.Home@503d687a]" started-at="2021-07-27T22:03:11 EET" name="close" finished-at="2021-07-27T22:03:11 EET" duration-ms="18" status="FAIL">
          <exception class="org.openqa.selenium.UnhandledAlertException">
            <message>
              <![CDATA[unexpected alert open: {Alert text : Email Incorrect}
  (Session info: chrome=92.0.4515.107): Email Incorrect
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-FQS4FE5', ip: '169.254.189.66', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 92.0.4515.107, chrome: {chromedriverVersion: 92.0.4515.43 (8c61b7e2989f2..., userDataDir: C:\Users\aliab\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:56024}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 0528664c77babdfa7a200cf574286cfb]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : Email Incorrect}
  (Session info: chrome=92.0.4515.107): Email Incorrect
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'DESKTOP-FQS4FE5', ip: '169.254.189.66', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 92.0.4515.107, chrome: {chromedriverVersion: 92.0.4515.43 (8c61b7e2989f2..., userDataDir: C:\Users\aliab\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:56024}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 0528664c77babdfa7a200cf574286cfb
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:442)
at Tests.Home.close(Home.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:676)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:660)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.UnhandledAlertException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Tests.Home -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
